local_backend: true

backend:
  name: github
  repo: jcutterwind/jcutterwind.github.io
  branch: main
  client_id: Ov23liUXdOT00sN00j7o

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # --- SHARED DATA ---
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image"}
      - {label: "YouTube URL (Optional)", name: "video", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Game Dev", "Music", "Cinematics", "Code"]}
      
      # --- ENGLISH CONTENT ---
      - label: "English Content"
        name: "en"
        widget: "object"
        fields:
          - {label: "Title (EN)", name: "title", widget: "string"}
          - {label: "Short Description (EN)", name: "description", widget: "text"}
          - {label: "Body (EN)", name: "body", widget: "markdown"}

      # --- ITALIAN CONTENT ---
      - label: "Italian Content"
        name: "it"
        widget: "object"
        fields:
          - {label: "Title (IT)", name: "title", widget: "string"}
          - {label: "Short Description (IT)", name: "description", widget: "text"}
          - {label: "Body (IT)", name: "body", widget: "markdown"}

